name: IOS
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
jobs:
  build_project:
    name: Build project
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: Nanopool.xcodeproj
          scheme: Nanopool
          destination: "'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=latest'"
          action: build